[phases.setup]
nixPkgs = [
  "php81",
  "php81Extensions.intl",
  "php81Extensions.zip",
  "php81Extensions.pdo_mysql",
  "php81Extensions.mbstring"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
